### ISSUE TITLE
CircularProgress  widget is not showing up

### ISSUE THREAD

**Issue by SourishBiswas23** [Aylur/astal#102]
**Describe the bug**
The CircularProgress widget is not visible in the bar. In the video provided below, the circular progress should be present between the cpu icon and the label 'Reading' but it doesnt show up.

**To Reproduce**
[A description or script to reproduce the behavior:](https://github.com/SourishBiswas23/ags-config/blob/main/widget/BarLeft/Cpu.tsx)

**Expected behavior**
The Circular Progress should appear between the cpu icon and the label 'Reading'

**Additional context**
ags version is 2.0.0
[Kooha-2024-11-17-15-07-26.webm](https://github.com/user-attachments/assets/bc8c30df-cb8b-47cf-b5aa-8dae4031d703)

**Comment by kotontrion** [comment]
you need to specify the size yourself either using min-height/min-width in css, or using heightRequest/widthRequest preoperties in js.

I made a PR which improves the size calculations.

**Comment by SourishBiswas23** [comment]
Thanks for clarifying this.
