### ISSUE TITLE
The end_widget in the centerbox is rendering widget at the center instead of rendering at the end

### ISSUE THREAD

**Issue by SourishBiswas23** [Aylur/astal#103]
**Describe the bug**
The title sums it up

**To Reproduce**
https://github.com/SourishBiswas23/ags-config/blob/main/widget/Bar.tsx

**Expected behavior**
The label 'End' in the attached video should render at the end of the bar not at the center of the bar

**Additional context**
ags v 2.0.0
[Kooha-2024-11-17-15-15-38.webm](https://github.com/user-attachments/assets/505e01f6-d712-4c2d-b8f7-43177d366b48)

**Comment by kotontrion** [comment]
the end_widget is a box. Boxes will expand to fill the whole width. Set `halign={Gtk.Align.END}` property for that box.

**Comment by SourishBiswas23** [comment]
Thanks again for clarifying this
