### ISSUE TITLE
How set windows hidden/invisible on ags run for toggle

### ISSUE THREAD

**Issue by mylinuxforwork** [Aylur/astal#107]
**Have you read through the documentation?**
- [x ] [Astal docs](https://aylur.github.io/astal/)
- [x ] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x ] [FAQ](https://aylur.github.io/astal/guide/ags/faq)

**Describe what have you tried so far**
I have build a calendar widget and I want to show it with the ags toggle. Toggle works fine but all windows are visible with ags run

**Describe your question**
How can I start ags run with hidden selected windows to toggle them later with ags run toggle?

**Comment by Aylur** [comment]
https://aylur.github.io/astal/guide/typescript/cli-app#toggling-windows-by-their-name

**Comment by Aylur** [comment]
you can make the window invisible at startup with
```js
<window visible={false} />
```

**Comment by mylinuxforwork** [comment]
> you can make the window invisible at startup with
> 
> ```js
> <window visible={false} />
> ```

Great. That’s what Inwas looking for. Thank you.
