### ISSUE TITLE
Wp.get_default_wp() causes a segfault

### ISSUE THREAD

**Issue by cuddleplush** [Aylur/astal#11]
Compiled from 71ee1ea4bf4edd790edb7067f8fb0ae6c450ce5e
Calling the wireplumber lib always causes a segfault, tested on default js config (simple-bar)

![image](https://github.com/user-attachments/assets/5820d90e-2cc5-4a12-a0f7-fb11e3e3afba)

```
pipewire --version                                                                                                                                                                              
 
pipewire
Compiled with libpipewire 1.2.3
Linked with libpipewire 1.2.3
```

```
wireplumber --version   
                                                                                                                                                                        
wireplumber
Compiled with libwireplumber 0.5.6
Linked with libwireplumber 0.5.6
```

I'm not very familiar with vala/c so I can't do much, but I can provide any additional logs/testing as necessary

**Comment by kotontrion** [comment]
could you provide the core dump?

**Comment by cuddleplush** [comment]
> could you provide the core dump?


[core.zip](https://github.com/user-attachments/files/17031892/core.zip)
Here you go

**Comment by kotontrion** [comment]
work on this is being done on the fix/wireplumber-11 branch.
please check if that solves the issue.

if not please provide more information, so i can try to reproduce this. like os, output of `wpctl status`

note that Wp.get_default_wp() was renamed to Wp.get_default().

**Comment by cuddleplush** [comment]
Yep, works perfectly now, thanks!
