### ISSUE TITLE
How to manage multiple widgets correctly?

### ISSUE THREAD

**Issue by iCultureBud** [Aylur/astal#111]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
I already set up a waybar-like widget (based on the bar example). Now I want to add more widgets to the screen (e.g. a controlcenter, mediaplayer, etc.) and they should align under the bar. 

**Describe your question**
Reading through the source code and docs didn't get me an answer. If I use a `window` for each widget I get a `GTK Warning`, but if I only use `box` the alignment is always center.

So what's the correct way to handle multiple widgets in one "app"? Just wrap all widgets into one `window` as `boxes` or each in just one `window`?

Thank you!

**Comment by Aylur** [comment]
In Gtk3 your only option is using windows

```tsx
function Bar() {
  function openPopup() {
    App.get_window("some-popup")!.show()
  }

  return <window>
    <box>
      <button onClicked={openPopup} />
    </box>
  </window>
}

function SomePopup() {
  return <window name="some-popup" application={App}>
  </window>
}

App.start({
  main() {
    Bar()
    SomePopup()
  }
})
```

You can enhance the popup with [click away to close](https://github.com/Aylur/ags/issues/63), or [press ESC to close](https://github.com/Aylur/astal/blob/3e6c7eeb1c96b5afba82f5fdc2ab35c78f383b38/examples/js/applauncher/widget/Applauncher.tsx#L53-L56)

In Gtk4 (not yet documented, and no JSX support yet) you can use the above window technique or you can also use [Gtk.Popover](https://docs.gtk.org/gtk4/class.Popover.html)
