### ISSUE TITLE
onClickRelease still activates despite cursor being off the button

### ISSUE THREAD

**Issue by uwidev** [Aylur/astal#120]
When a button is registered for `onClickRelease`, how it works for most UIs is that when you click on the button, if you change your mind you can move off of the button and release to not proceed with the action. The current behavior does not follow this. If you press a button and change mind, move the cursor off the button and release, the button will activate regardless.

Not sure if this is intentional or not, but it currently does not function as I would have expected from previous standards.

**Comment by Aylur** [comment]
This is just how Gtk works. Use a button widget and the `clicked` signal if you want the behavior you described.
