### ISSUE TITLE
Adding river tags to a bar

### ISSUE THREAD

**Issue by lanovets** [Aylur/astal#122]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
A description or example code of what you have got so far.

**Describe your question**
How to add river tags to a bar? I read through library references for astal-river and still don't know how to do this. Thank you.

**Comment by kotontrion** [comment]
Rivers tags are output specific, so you need to get the River.Output object, either by name using `get_output(name)` or by using the `outputs` list. The the output object has `occupied-tags`, `focused-tags` properties, which are bitmasks, basically the same as used by riverctl. 

Here is my river tags widget implementation in vala.

https://github.com/kotontrion/kompass/blob/main/kompass%2Fsrc%2Ftags.vala
