### ISSUE TITLE
Properly disconnecting a `Binding`?

### ISSUE THREAD

**Issue by vafu** [Aylur/astal#132]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq) 

**Describe what have you tried so far**
If a BindingA  (`focusedClient`) returns a BindingB (`class`), and you subscribe to a BindingB in `subscribe`  of BindingA, once BindingA emits a new value, subscription to BindingB will be lost and there's no easy way to handle it. It should be disconnected.
```
    const activeWindow = Variable("")
    bind(hypr, "focusedClient").subscribe(w => {
        if (w != null) {
            bindWindow(w)
        } else {
            bind(w, "class").subscribe(cls => activeWindow.set(cls))
        }
    })
```
Would be nice to have something like [switchMap](https://rxjs.dev/api/operators/switchMap). 

It is possible to do `const id = connect("notify::class", () => {})` and then handle the connection with `disconnect(id)`, but that beats the purpose of a super convinient `Binding`.

**Comment by vafu** [comment]
I actually thinking maybe it won't be hard to wrap `Connectable` into `Observable` (because it essentially is an Observable), that'll allow to use all the convenience operators Rx has to offer. 
I'll try that now

**Comment by pynappo** [comment]
If i'm not mistaken, binding will return a function that disconnects from the underlying connectable

https://github.com/Aylur/astal/blob/b7af61d770510b1c797e1c7137a4da934cdca7a2/lang/gjs/src/binding.ts#L76-L84

It's just not particularly documented but seems to work in my config

**Comment by vafu** [comment]
fair point, but that's the same problem as with ids, would be nice to have this automatically handled similar to switchmap

**Comment by vafu** [comment]
ok, happy to say Rx bindings work like a charm

```
// creates observable from given connectable property
export function observable<
    T extends Connectable,
    P extends keyof T,
>(object: T, property: P): Observable<T[P]> {
    return asObservable(bind(object, property))
}

// creates observable from given binding, starting the chain with value already present in binding (if present)
export function asObservable<Value>(binding: Binding<Value>): Observable<Value> {
    return Observable.create(o => {
        const initial = binding.get()
        if (initial != null) o.onNext(initial)
        return Disposable.create(
            binding.subscribe(value => o.onNext(value))
        )
    })
}

// converts observable to Binding by mapping Binding#subscribe to Observable#subscribe, as well as remembers emitted value to share from `get`. 
export function asBinding<T>(observable: Observable<T>): Binding<T> {
    let value: T | null
    const shared = observable
        .doOnNext(v => value = v)
        .replay()
        .refCount()

    return bind({
        subscribe: (callback) => shared.subscribe(callback).dispose,
        get: () => value,
    })
}
```

and then the usage is 
```
// creating an observable from "focusedClient" signal and sharing it
const focusedClient = observable(AstalHyprland.get_default(), "focusedClient").replay().refCount()

// whenever focused client changes, we start listening to the latest observable of the "class" and "title" signal, representing active window class/title
const cls = focusedClient.flatMapLatest(client => observable(client, "class"))
const title = focusedClient.flatMapLatest(client => observable(client, "title"))

export const WindowTitle = () => <Box className="window-title bar-widget">
    <Label
        className="cls"
        // create a single lable, that listens to a stream of "active window class" 
        label={asBinding(cls)}
    />
    <Label
        // create a single lable, that listens to a stream of "active window title" 
        label={asBinding(title)}
    />
</Box>
```

using rx-ts is such a game changer imo!!
it allows to create complex data pipes and easily render those with astal widgets
