### ISSUE TITLE
Privacy indications

### ISSUE THREAD

**Issue by danielwerg** [Aylur/astal#133]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [ ] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**

Just had a glance at wireplumber library, but thought somebody might have already implemented this. Don't want to reinvent the wheel.

Not sure how to filter out streams, `wpctl` has `<` or `>` for stream direction and `[active]` or `[paused]` for state, couldn't find this in wireplumber astal lib.

Also don't know how to detect screensharing, I was testing with https://screensy.marijn.it

**Describe your question**

Privacy indications

Indicators if the mic is accessed, any application is playing sound, and if the screen is being shared

I used this module in waybar: https://github.com/Alexays/Waybar/wiki/Module:-Privacy

![](https://github.com/user-attachments/assets/ddd65976-b82c-42aa-a387-09d25cb4f26f)
![](https://github.com/user-attachments/assets/23fcbddf-40ca-4264-ab68-cf3c880d93a0)

**Comment by kotontrion** [comment]
The astal-wireplumber lib contains two object, audio and video, which basically act as filters.
Both of them have a streams property, which contains output streams, and a recorders property, which contains input streams. Using this makes a privacy indicator quite easy to implement. 
I quickly wrote something which gets you close to those screenshots.

```js
import AstalWp from "gi://AstalWp"

const {audio, video} = AstalWp.get_default()!;

function PrivacyIndicator({obj, type} : {obj: AstalWp.Audio | AstalWp.Video, type: "recorders" | "streams"}){
  return (
    <icon 
      visible={bind(obj, type).as(list => list.length > 0)}
      icon={type == "recorders" ? "audio-input-microphone-symbolic" : "audio-speakers-symbolic"}
      tooltipText={bind(obj, type).as(list => list.map(e => e.name).join("\n"))}
    />
  );
}

function PrivacyModule() {
  return (
    <box>
      <PrivacyIndicator obj={audio} type="recorders"/>
      <PrivacyIndicator obj={audio} type="streams"/>
      <PrivacyIndicator obj={video} type="recorders"/>
      <PrivacyIndicator obj={video} type="streams"/>
    </box>
  );
}
```

Note however that it can only detect screenrecording if the pipewire api is used, so eg it won't detect wf-recorder.

There is currently no way to get the state of the stream. This is not implemented yet as the goal of this was to get feature parity with the previous audio lib, which it achieved. Adding more functionality like this is on my todo list though.

**Comment by danielwerg** [comment]
Thank you!

This still lists everything regardless of a state (`[active]` or `[paused]`).  I can't find anything on `AstalWp.Endpoint`. Am I missing something?

**Comment by danielwerg** [comment]
Also I not sure how to add icons to tooltip, `tooltipText` only accepts strings. Looking at https://github.com/Aylur/ags/discussions/536 and https://github.com/Aylur/ags/discussions/303 right now. Oh, just found `Gtk.Menu` `popup_at_widget`.

**Comment by kotontrion** [comment]
> This still lists everything regardless of a state ([active] or [paused]). I can't find anything on AstalWp.Endpoint. Am I missing something?

Read the last paragraph of my comment again. This is not implemented yet.

> Also I not sure how to add icons to tooltip

Gtk provides the `tooltip_text` and `tooltip_markup` properties for ease of use.
If you want more complex tooltips you can set custom widgets in the tooltip. To do this you need to connect to the query_tooltip signal liek this:

```js
import AstalWp from "gi://AstalWp"

const {audio, video} = AstalWp.get_default()!;

function PrivacyTooltip(eps: AstalWp.Endpoint[]) {
  return (
    <box vertical>
      {eps.map(ep => {
        return (
          <box>
            <icon icon={ep.icon} />
            <label label={ep.name} />
          </box>
        );
      })}
    </box>
  );
}

function PrivacyIndicator({obj, type} : {obj: AstalWp.Audio | AstalWp.Video, type: "recorders" | "streams"}){
  return (
    <icon 
      visible={bind(obj, type).as(list => list.length > 0)}
      icon={type == "recorders" ? "audio-input-microphone-symbolic" : "audio-speakers-symbolic"}
      has_tooltip={true}
      onQueryTooltip={(self, x, y, kbtt, tooltip) => {
        tooltip.set_custom(PrivacyTooltip(obj[type]));
        return true;
      }}
    />
  );
}

function PrivacyModule() {
  return (
    <box>
      <PrivacyIndicator obj={audio} type="recorders"/>
      <PrivacyIndicator obj={audio} type="streams"/>
      <PrivacyIndicator obj={video} type="recorders"/>
      <PrivacyIndicator obj={video} type="streams"/>
    </box>
  );
}
```
Note that this requires the gjs bindings from the newest commit, as I just added the list getter workarounds or AstalWp.

**Comment by danielwerg** [comment]
I can't read.. Sorry :)

> Note that this requires the gjs bindings from the newest commit, as I just added the list getter workarounds or AstalWp.

Hmm, works for me on latest aur. Unless I'm missing something again :|

Also is there a reason `-git` packages are not auto published with github action?

---

`endpoints.icon` almost always is `application-x-executable-symbolic` so I added a function that gets icon name from `endpoint.description`, didn't work with mumble since both `endpoint.name` and `endpoint.description` are either `Capture` or `Playback`. `wpctl inspect` has this field: `application.name = "Mumble"` but I guess this also not implemented in astal lib.

**Comment by kotontrion** [comment]
> Also is there a reason -git packages are not auto published with github action?

This is not how the AUR works.
`-git` packages always build the newest commit regardless of what the pkgver says (this will actually be updated on install). It is the package managers responsibility to check if there are upstream changes. `paru` checks that by default.For `yay` you need to specify the `--devel` parameter.

**Comment by danielwerg** [comment]
What about:

> `wpctl inspect` has this field: `application.name = "Mumble"` but I guess this also not implemented in astal lib.

Should I open separate issue to track that?
