### ISSUE TITLE
MPRIS Fails to Cache Cover Art for Spotify

### ISSUE THREAD

**Issue by calebstewart** [Aylur/astal#136]
**Describe the bug**
When using the example MPRIS Media Player widget, it works perfectly when the player is (for example) YouTube in Firefox. The cover art is loaded as the thumbnail of the video that was playing. However, when the player is the official Spotify client, the cover art does not display, and the following error is logged:

```
** (gjs:1175049): CRITICAL **: 17:54:17.226: player.vala:531: Failed to cache cover art with url "https://i.scdn.co/image/ab67616d0000b27388d03ef62aac9bfebfbee9d7": Operation not supported
```

When this happens, the widget still works, but there is no album/cover art.

**To Reproduce**
Run the example MPRIS media player widget ([ref](https://github.com/Aylur/astal/tree/main/examples/js/media-player)) and use the official Spotify desktop client.

**Expected behavior**
The cover art is cached the same as w/ YouTube.

**Additional context**
Output of `ags --version`:

```
$ ags --version
ags version 2.1.0
```

And this is my `flake.lock` for granular version reference:
```json
{
  "nodes": {
    "ags": {
      "inputs": {
        "astal": "astal",
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1731966249,
        "narHash": "sha256-9hDeMy6S2q1wWBFGiJic5yUms19zW8LhAX9MlCtuN6k=",
        "owner": "aylur",
        "repo": "ags",
        "rev": "12e0bfefd2051c43d7450123fcb095f655b891e8",
        "type": "github"
      },
      "original": {
        "owner": "aylur",
        "repo": "ags",
        "type": "github"
      }
    },
    "astal": {
      "inputs": {
        "nixpkgs": [
          "ags",
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1731952585,
        "narHash": "sha256-Sh1E7sJd8JJM3PCU1ZOei/QWz97OLCENIi2rTRoaniw=",
        "owner": "aylur",
        "repo": "astal",
        "rev": "664c7a4ddfcf48c6e8accd3c33bb94424b0e8609",
        "type": "github"
      },
      "original": {
        "owner": "aylur",
        "repo": "astal",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1731676054,
        "narHash": "sha256-OZiZ3m8SCMfh3B6bfGC/Bm4x3qc1m2SVEAlkV6iY7Yg=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "5e4fbfb6b3de1aa2872b76d49fafc942626e2add",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "ags": "ags",
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

**Comment by Aylur** [comment]
perhaps you forgot this?
![image](https://github.com/user-attachments/assets/75450bb0-fd35-4425-a2ed-67765da28158)
[bottom of the mpris page](https://aylur.github.io/astal/guide/libraries/mpris#installation)

**Comment by calebstewart** [comment]
Damn it. I hate when I'm *that* guy. I apologize for wasting your time, and thank you for politely telling me to RTFM. :stuck_out_tongue_closed_eyes:  I've been in and out of these docs all day, and somehow missed or forgot about that very obvious and helpful warning.
