### ISSUE TITLE
error: packages failed to build: libastal-cava-git-r501.078dc04-1

### ISSUE THREAD

**Issue by Firebleudark** [Aylur/astal#139]
I'm on ArchLinux,

When I update the package libastal-cava-git with paru, I have this error : 
'''==> Making package: libastal-cava-git r501.078dc04-1 (Tue 26 Nov 2024 07:49:07 PM CET)
==> Retrieving sources...
  -> Updating astal git repo...
==> Validating source files with sha256sums...
    astal ... Skipped
==> Making package: libastal-cava-git r501.078dc04-1 (Tue 26 Nov 2024 07:49:07 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating astal git repo...
==> Validating source files with sha256sums...
    astal ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of astal git repo...
Cloning into 'astal'...
done.
fatal: invalid reference: origin/feat/cava
==> ERROR: Failure while creating working copy of astal git repo
    Aborting...
error: failed to build 'libastal-cava-git-r501.078dc04-1':
error: packages failed to build: libastal-cava-git-r501.078dc04-1'''

Can you solved this ?

**Comment by kotontrion** [comment]
fixed.

**Comment by Enceka** [comment]
Same as you.Seemd missing branch _feat/cava_(I dont know anything about this)
But It works fine when I modified the PKGBUILD file,delete _#branch=feat/cave_.
Then you can use _makepkg -si_

**Comment by kotontrion** [comment]
Yeah it did build from that branch before the merge. When it got merged I forgot to update the pkgbuild. I deleted the branch today to clean up the repo a bit. This broke the package. I updated the pkgbuild already.
You might need to wait a while until you can update because of caching.

**Comment by Firebleudark** [comment]
Perfect ! Work for me !
