### ISSUE TITLE
Battery icon is innaccurate and doesn't match ags

### ISSUE THREAD

**Issue by brainlessbitch** [Aylur/astal#14]
battery at 30% in astal
![image](https://github.com/user-attachments/assets/bdd83295-db40-4a1c-8277-e162c5e11784)
battery at 30% in ags
![image](https://github.com/user-attachments/assets/486805bd-fa61-46eb-9d54-2b50ebd1516c)
the astal icons feel less accurate, and i feel it'd be better to match ags

**Comment by Aylur** [comment]
[icon_name](https://aylur.github.io/libastal/battery/method.Device.get_icon_name.html) is the icon reported by upowerd
[battary_icon_name](https://aylur.github.io/libastal/battery/method.Device.get_battery_icon_name.html) is what matches the ags icon
