### ISSUE TITLE
Hyprland service's Active Workspace for a Monitor is not updating.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [Aylur/astal#147]
**Describe the bug**
Whenever you change a workspace for a monitor, that monitor's `activeWorkspace` property does not get updated. If, on monitor 0,  go from workspace 1 to 3. It remains on 1, which is the value it started with.

**To Reproduce**
```ts
import AstalHyprland from 'gi://AstalHyprland?version=0.1';
const hyprlandService = AstalHyprland.get_default();

Variable.derive([bind(hyprlandService.get_monitors()[0], 'activeWorkspace')], (ws) => {
    console.log(ws.id);
});

```
Put that in your code and change between multiple workspaces for the monitor at index 0. Notice that the log keeps showing the same workspace over and over.

**Expected behavior**

The `activeWorkspace` for the monitor is updated whenever the workspace is changed.

**Comment by Aylur** [comment]
dup https://github.com/Aylur/astal/issues/130
are you sure you are up to date?

**Comment by Jas-SinghFSU** [comment]
I had thought I did and it still persisted. Ended rebuilding which fixed it, so definitely PEBCAK. 

Apologies.
