### ISSUE TITLE
How to get mpris year

### ISSUE THREAD

**Issue by danielwerg** [Aylur/astal#149]
**Have you read through the documentation?**

- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**

```sh
playerctl metadata --format "{{xesam:contentCreated}}"
```

**Describe your question**

How do I get `year` or `contentCreated`? `Mpris.Player` doesn't seem to have anything same goes for `Mpris.Player.get_metadata()`.

**Comment by Aylur** [comment]
you can use [get_meta](https://aylur.github.io/libastal/mpris/method.Player.get_meta.html)
```js
player.get_meta("xesam:contentCreated")?.get_string()
```

**Comment by danielwerg** [comment]
ah, so can't bind properly still
