### ISSUE TITLE
Ignore 'undefined' properties in the 'astalify' constructor

### ISSUE THREAD

**Issue by plsmphnx** [Aylur/astal#151]
**Is your feature request related to a problem? Please describe.**
Passing optional properties as a JSX attribute (e.g. doing something like `<window monitor={monitor?.id} />`) will result in an error along the lines of "JS ERROR: Error: Wrong type undefined; ... expected".

**Describe the solution you'd like**
Have the constructor generated by the `astalify` function ignore undefined properties (along the lines of how it ignores falsy children), probably by filtering them out prior to the final `Object.assign`.

**Describe alternatives you've considered**
This can be worked around by either wrapping the entire widget in a conditional or doing hacks like passing properties via `{...(m != null ? { monitor: m } : {})}`, but both solutions are somewhat unwieldy.

**Comment by Aylur** [comment]
note that null values are not filtered, because `null` is usually passed explicitly which usually should be handled by the user
