### ISSUE TITLE
How to change color of custom svg icon?

### ISSUE THREAD

**Issue by danielwerg** [Aylur/astal#153]
**Have you read through the documentation?**

- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**

```scss
icon {
  color: red; // works with gtk theme icons
}
```

coffee.svg:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
  stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-coffee">
  <path d="M18 8h1a4 4 0 0 1 0 8h-1"></path>
  <path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"></path>
  <line x1="6" y1="1" x2="6" y2="4"></line>
  <line x1="10" y1="1" x2="10" y2="4"></line>
  <line x1="14" y1="1" x2="14" y2="4"></line>
</svg>
```

```tsx
<icon icon="coffee" />
```

Will render stroke in black instead of red.

```tsx
<icon icon="coffee" css="color: green"  /> // same thing
```

**Describe your question**

https://aylur.github.io/astal/guide/typescript/faq#custom-svg-symbolic-icons

**Comment by kotontrion** [comment]
Gtk will only color symbolic icons.
So you have to name the file `coffee-symbolic.svg` and use `coffee-symbolic` as icon name.

**Comment by danielwerg** [comment]
hmm, thought it was just a convention I could ignore, thanks!

But now color applies to `fill` and not `stroke`, svg has `fill="none" stroke="currentColor"`

![image](https://github.com/user-attachments/assets/8b84da5f-5aec-4e04-90b1-1edc70fe8815)
^ Sets fill to `red` and stroke to `black`
https://feathericons.com/?query=coffee

Maybe I messed up something on my end, haven't touch the codebase since I opened this issue...

**Comment by kotontrion** [comment]
Yeah, gtk will only change the color of fill. symbolic icons are supposed to be monochrome with no stroke.

**Comment by danielwerg** [comment]
I guess I will have to have duplicated icon to change colors then.
