### ISSUE TITLE
[Question] How to bind to all individual device events for Bluetooth Service?

### ISSUE THREAD

**Issue by Jas-SinghFSU** [Aylur/astal#155]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
Binding to 'devices' or 'notify'.

**Describe your question**

> Copy Pasting from Discord since Discord is a pretty siloed communication platform

I am currently rendering a list of Bluetooth devices in which the `Paired` or `Connected` devices are visible at the very top of the list. This is determined by the individual Device's `conntected` or `paired` boolean property.

I can then connect to or disconnect from a device which should either add-to/remove-from the top of this device list. Issue is that binding to the AstalBluetooth 'devices' signal does not trigger when individual devices within it are changed. This was possible in AGSv1 via `self.hook(bluetooth....` However that doesn't seem to be currently possible.

My question is, how can I make a top level binding that captures all events so that anytime an **individual device** in my list is connected/paired, it can be pushed to the top of my listed immediately.

Here is some code for reference:
```ts
    return (
        <box className={'menu-items-section'}>
            <box className={'menu-content'} vertical>
                {Variable.derive([bind(bluetoothService, 'devices'), bind(bluetoothService, 'isPowered')], () => {
                    const availableDevices = getAvailableBluetoothDevices();
                    const connectedDevices = getConnectedBluetoothDevices();

                    if (availableDevices.length === 0) {
                        return <NoBluetoothDevices />;
                    }

                    if (!bluetoothService.adapter.powered) {
                        return <BluetoothDisabled />;
                    }

                    return availableDevices.map((btDevice) => {
                        return <DeviceListItem btDevice={btDevice} connectedDevices={connectedDevices} />;
                    });
                })()}
            </box>
        </box>
    );
```
```ts
export const getAvailableBluetoothDevices = (): AstalBluetooth.Device[] => {
    const availableDevices = bluetoothService.devices
        .filter((btDev) => btDev.name !== null)
        .sort((a, b) => {
            if (a.connected || a.paired) {
                return -1;
            }

            if (b.connected || b.paired) {
                return 1;
            }

            return a.name.localeCompare(b.name);
        });

    return availableDevices;
};
```

**Comment by Aylur** [comment]
Best approach here is to create a custom [subscribable](https://aylur.github.io/astal/guide/typescript/binding#example-custom-subscribable) class

```ts
class BtDevices implements Subscribable {
  #list = Variable<Device[]>([])
  #connection: number

  #getAvailableBluetoothDevices(): Device[] {
    // your sorting algorithm
  }

  #update() { this.#list.set(this.#getAvailableBluetoothDevices()) }

  constructor() {
    // listen for new devices and listen to their prop changes
    this.#connection = bluetooth.connect("device-added", (_, device) => {
      const ids = [
        device.connect("notify::connected", () => this.#update()),
        device.connect("notify::paired", () => this.#update()),
      ]
      // cleanup
      const id = bluetooth.connect("device-removed", (_, d) => {
        if (d == device) {
          ids.map(id => device.disconnect(id))
          bluetooth.disconnect(id)
          this.#update()
        }
      })
      this.#update()
    })
    this.#update()
  }

  drop() {
    bluetooth.disconnect(this.#connection)
    this.#list.drop()
  }

  subscribe(callback: (list: Device[]) => void) {
    this.#list.subscribe(callback)
  }

  get() {
    return this.#list.get()
  }
}
```

quite a mouthful compared to v1 I know, but this way you have finegrained control over when rerendering happens

```jsx
function() {
  const devices = new BtDevices()
  
  return <box onDestroy={() => devices.drop}>
    {bind(devices).as(devices => devices.map(device => (
      <DeviceWidget device={device} />
    )))}
  </box>
}
```

a major thing to note here is that this will still rerender a lot, so what you might want to do is create the device widgets in the `BtDevices` class itself similar to the [notification example](<https://github.com/Aylur/astal/blob/4c19d8d06fa25cc6389f37abe8839b4d8be5c0d6/examples/js/notifications/notifications/NotificationPopups.tsx#L13>) and only reorder the widgets inside the list instead of recreating them each time

also, fyi doing `bind(Variable.derive([bind(), bind()]))` is [not recommended](https://aylur.github.io/astal/guide/typescript/variable#dispose-if-no-longer-needed), due to it leaking memory, since it won't be collected when the widget is destroyed

**Comment by Jas-SinghFSU** [comment]
> also, fyi doing bind(Variable.derive([bind(), bind()])) is [not recommended](https://aylur.github.io/astal/guide/typescript/variable#dispose-if-no-longer-needed), due to it leaking memory, since it won't be collected when the widget is destroyed

Hmm, not sure I follow but I'd like to fix this if it's true. Are you saying that anytime a variable is derived, if the parent widget of the derivation container is destroyed, the Variable is never dropped? If so then I should probably handle the `drop` of the variable. However, in this case if the box that contains this binding is static, it would be safe to use this pattern right? Considering that "theoretically" this widget will never be deleted?
