### ISSUE TITLE
Do Gtkwidgets still work in V2?

### ISSUE THREAD

**Issue by RylanGotto** [Aylur/astal#158]
# Embedding GtkSourceView into a Scrollable Element in v2

Hello, I just had a quick question regarding embedding `GtkSourceView` into a scrollable element in v2?

### Code for `CovertToSourceView`

```typescript
const CovertToSourceView = (content: string) => {
    const buffer = new GtkSource.Buffer();
    const sourceView = new GtkSource.View({
        buffer: buffer,
    });
    const langManager = GtkSource.LanguageManager.get_default();
    const lang = langManager.get_language('python'); 
    buffer.set_language(lang);
    const schemeManager = GtkSource.StyleSchemeManager.get_default();
    buffer.set_style_scheme(schemeManager.get_scheme('classic'));
    buffer.set_text(content, content.length);

    return sourceView;
}

<box className="chat-history" vertical>
    <scrollable className="chat-box" child={CovertToSourceView(item.text)}>
    </scrollable>
</box>

or 

<box className="chat-history" vertical>
    <scrollable className="chat-box">
        {CovertToSourceView(item.text)}
    </scrollable>
</box>
```
I have tried both implementations; however, I cannot seem to get it to render. Any guidance would be greatly appreciated!

**Comment by kotontrion** [comment]
A common issue with scrollables is that they just don't request any height. So try adding `vexand` or `height-request` to the scrollable, maybe also look into `propagate-natural-height` and `max-content-height` properties.

Using the inspector is helpful in such cases.

**Comment by RylanGotto** [comment]
thank you for your reply. I will give your suggestions a shot. I have been using the inspector and everything indicated that should be render. I will give you suggestion a try and report back. Thanks again for your time.

**Comment by kotontrion** [comment]
Oh wait, you don't use `astalify`. 
In Gtk3 all widgets are not visible by default. `astalify` changes this, so I forgot about it. Set the `visible` property of the SourceView to true
