### ISSUE TITLE
GTK4 label properties do not accept Variables

### ISSUE THREAD

**Issue by ghost** [Aylur/astal#162]
**Describe the bug**
When setting the label property of a GTK4 widget to a `Variable`, GJS errors out with this message:
`Gjs-CRITICAL **: <timestamp>: JS ERROR: Error: Wrong type Object; string expected`

**To Reproduce**
```ts
#!/usr/bin/env -S ags run --gtk4

import { Variable } from "astal"
import { App, Astal, Gtk } from "astal/gtk4"

App.start({
  instanceName: "qishr",
  main: () => {
    const { TOP, LEFT, RIGHT } = Astal.WindowAnchor;
    
    const time = Variable("").poll(1000, "date")

    new Astal.Window({
      anchor: TOP | LEFT | RIGHT,
      application: App,
      exclusivity: Astal.Exclusivity.EXCLUSIVE,
      visible: true,
      child: new Gtk.CenterBox({
        startWidget: new Gtk.Button({label: time()}),
      })
    })
  },
})
```
**Expected behavior**
I expected
1. The window to show up(the gtk app crashed)
2. The button's label to auto-update

**Additional context**
<details>
<summary>Full error on gjs's side</summary>

```
(gjs:377155): Gjs-CRITICAL **: 15:54:39.135: JS ERROR: Error: Wrong type Object; string expected
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:39:56
```
</details>

<details>
<summary>nix flake metadata</summary>

```
ags: github:aylur/ags/81159966eb8b39b66c3efc133982fd76920c9605
|───astal follows input 'astal'
|───nixpkgs follows input 'nixpkgs'
astal: github:ys5g/astal/d93ec805170bec53cd6d8d86add2d12d1c17048f
|───nixpkgs follows input 'nixpkgs'
nixpkgs: github:nixos/nixpkgs/76612b17c0ce71689921ca12d9ffdc9c23ce40b2
```
</details>

**Comment by kotontrion** [comment]
Gtk widgets cant consume variables or bindings. This is  an astal thing. the gtk4 version of astal does not have an `astalify` function yet. So you can't do this yet. Either wait until astals gjs bindings are more mature or if you want to use gtk4 now, look at blueprint or connect to the signals instead of using binds.

**Comment by ghost** [comment]
EDIT: After #196, you don't need a custom astalify.ts for gtk4
I got the typescript approach to work using an adapted version of Vafu's [PR](#85) for gtk4 support in gjs([link to his astalify.ts](https://github.com/vafu/astal/blob/vafu/gtk4-widget/lang/gjs/src/gtk4/astalify.ts)). [Here's the gist](https://gist.github.com/ys5g/20e5c03cac665e940bbe62e7beca9ab9) 
<details>
<summary>About the blueprint approach...</summary>

I got the same error(`Wrong type Object; string expected`) with blueprint and I can't find a fix

```blp
using Gtk 4.0;

using Astal 4.0;
using AstalIO 0.1;

template $Bar: Astal.Window {
  exclusivity: exclusive;

  CenterBox {
    [center]
    Label { label: bind (template.date as <AstalIO.Variable>).value; }
  }
}
```
```ts
// Bar.ts
import { Variable } from "astal"
import { Astal, App } from "astal/gtk4"
import { GLib, register, property } from "astal/gobject"
import Template from "../ui/Bar.blp"

@register({ GTypeName: "Bar", Template })
class _Bar extends Astal.Window {
  @property(String)
  declare date: string;
}

export const Bar = () => {
  const { TOP, LEFT, RIGHT } = Astal.WindowAnchor;
  
  const time = Variable("").poll(1000, "date '+%I:%M:%S %p - %m/%d/%Y'")

  new _Bar({
    anchor: TOP | LEFT | RIGHT,
    application: App,
    visible: true,
    date: time(),
  })
}
```
```ts
#!/usr/bin/env -S ags run --gtk4
// app.ts

import { App, Astal } from "astal/gtk4"
import { Bar } from "./widget/Bar.ts"

App.start({
  instanceName: "qishr",
  main: Bar(),
})
```
</details>

**Comment by kotontrion** [comment]
> date: time()

Well this creates a binding object, dont do this. Property bindings are handled completely and alone be blueprint.

The bars date property should be of type Variable, then do `date = Variable("").poll(...)`

**Comment by ghost** [comment]
Thanks for your time. 
Just replacing the `date: time()`(in `new _Bar({})`) with `date: Variable("").poll(1000, "date")` gave me `JS ERROR: Error: Wrong type Proxy; string expected`
Was there anything else I needed to change?

**Comment by kotontrion** [comment]
```js
@register({ GTypeName: "Bar", Template }) 
class _Bar extends Astal.Window { 
  @property(String) 
  declare date: string;
}
```
You also need to change the type of the date property to Variable.

I never used blueprint with js and i don't know how exactly those decorators work though.

**Comment by ghost** [comment]
Sorry for the pings.
["Subclassing" on gjs.guide](https://gjs.guide/guides/gobject/subclassing.html#properties) might help

Just for the record, I am aware that the `Variable` class from "astal" is not the same as the `Variable` class from AstalIO. Is that the latter the only way to get this to work?

For anyone following this, neither of these work:

Approach 1
```ts
// ...
import { GObject, register, property } from "astal/gobject"
import AstalIO from "gi://AstalIO?version=0.1"
// ....
@register({ GTypeName: "Bar", Template })
class _Bar extends Astal.Window {
  @property(GObject.Object)
  declare date: AstalIO.Variable
}
// ....
```
<details>
<summary>Error for this approach</summary>

I'm guessing that  `Object 0x3c686d63ac0` is `Variable("").poll(1000, "date '+%I:%M:%S %p - %m/%d/%Y'")`

```
(gjs:432131): Gjs-CRITICAL **: 12:10:50.116: JS ERROR: TypeError: Object 0x3c686d63ac0 is not a subclass of GObject_Object, it's a Proxy
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:39:56
_Bar@file:///run/user/1001/ags.js:515:12
Bar@file:///run/user/1001/ags.js:526:3
@file:///run/user/1001/ags.js:537:9

Caused by: Error: This JS object wrapper isn't wrapping a GObject. If this is a custom subclass, are you sure you chained up to the parent _init properly?
```
</details>


Approach 2
```ts
// ...
import { GObject, register, property } from "astal/gobject"
import AstalIO from "gi://AstalIO?version=0.1"
// ....
@register({ GTypeName: "Bar", Template })
class _Bar extends Astal.Window {
  @property(GObject.ParamSpec.object) // Change is here
  declare date: AstalIO.Variable
}
// ....
```
<details>
<summary>Error for this approach</summary>

```
(gjs:432246): Gjs-CRITICAL **: 12:13:57.060: JS ERROR: Error: Expected type object for argument 'object_type' but got type undefined
```
</details>

**Comment by Aylur** [comment]
You just don't need the variable in this case at all
Define your property as a string
```ts
import { interval } from "astal/time"

class Bar extends Astal.Window {
  private interval: AstalIO.Time
  @property(String) declare date: string
  
  construct() {
    super()
    this.interval = interval(1000, () => {
      this.date = new Date().toString()
    })
  }
  
  on_destroy() {
    this.interval.cancel()
  }
}
```

and in you template
```blp
CenterBox {
  [center]
  Label { label: bind template.date; }
}
```
