### ISSUE TITLE
How do you build Astal + Ags in Nix

### ISSUE THREAD

**Issue by PixeKnight** [Aylur/astal#169]
I tried to copy the given code:
```
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    astal = {
      url = "github:aylur/astal";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    ags = {
      url = "github:aylur/ags";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, astal, ags }: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in {
    packages.${system}. default = pkgs.stdenvNoCC.mkDerivation rec {
      name = "my-shell";
      src = ./.;

      nativeBuildInputs = [
        ags.packages.${system}.default
        pkgs.wrapGAppsHook
        pkgs.gobject-introspection
      ];

      buildInputs = with astal.packages.${system}; [
        astal3
        io
        # any other package
      ];

      installPhase = ''
        mkdir -p $out/bin
        ags bundle app.ts $out/bin/${name}
      '';
    };
  };
}
```
from the wiki to a flake.nix in an "astal" directory, but when I run `nix build .`, it fails at the install phase "error: stat /build/astal/app.ts: no such file or directory".

Sorry if this is user error, I haven't found that many guides on how to make your own nix packages.

I am without a doubt certain that it fails on the very last line, that line being 
`ags bundle app.ts $out/bin/${name}`

I thought it might be to do with an existing ags package I had installed, but no, it failed even after removing all ags packages.

**Comment by PixeKnight** [comment]
Oh, am I supposed to have the ags files in that /build/astal/ folder?

**Comment by PixeKnight** [comment]
Nvm, that didn't work

**Comment by Aylur** [comment]
lgtm, I'm pretty sure you just named your entry file something else
you could have a look at [`ags.lib.bundle`](https://github.com/Aylur/ags/blob/main/nix/bundle.nix)
