### ISSUE TITLE
Publishing .gir files?

### ISSUE THREAD

**Issue by hyperparabolic** [Aylur/astal#17]
I'm playing around with rust bindings, and generating them from .gir files seems the least painful way to do it.

I'd be fine with most distribution methods. I don't think manual processes are really viable here with how often things are being updated.

How would you feel about a `astal-dev` or `astal-girs` package that includes all of the .gir files in a single package? I know they could technically all just be published to `/usr/share/gir-1.0/` in each individual meson.build file, but it's really clunky while working in nixos. `Gir.toml` needs to know about each directory that includes .gir files, so that's probably 13 symlinks into the nix store at the moment, and more if more services are added.

I'm not a meson pro, but I could try to hack something like that together if you don't have time for it. Let me know what you think, or if there's some other way you'd want to distribute them that you'd prefer.

**Comment by Aylur** [comment]
Each library installs their gir to `prefix/datadir/gir-1.0` so usually `/usr/share/gir-1.0/`, so for example for Arch the AUR meta package is already a single distribution for all gir files.
This separation is by design. I don't know how rust bindings work, but I don't think we need a collective package, there are multiple libraries, so multiple bindings will be needed

**Comment by Aylur** [comment]
Although, there will be a tagged release at some point in which case we could have a collective package, but I'm not sure if that helps on Nix

**Comment by hyperparabolic** [comment]
> Each library installs their gir to `prefix/datadir/gir-1.0` so usually `/usr/share/gir-1.0/`, so for example for Arch the AUR meta package is already a single distribution for all gir files. This separation is by design. I don't know how rust bindings work, but I don't think we need a collective package, there are multiple libraries, so multiple bindings will be needed

Okay, yeah, that's very idiomatic. It looks like my initial pass at a flake wasn't bulding the `*-dev` packages. That's my bad.

> Although, there will be a tagged release at some point in which case we could have a collective package, but I'm not sure if that helps on Nix

I think that might just be it. Even on nixos, what's here looks like it's workable as long as the semver is incremented:

```
$ ls /nix/store/*astal*-dev/share/gir-1.0/*.gir
/nix/store/19d411hwsb477ys7g8n480fzbdimzh3q-astal-wireplumber-0.1.0-dev/share/gir-1.0/AstalWp-0.1.gir
/nix/store/9vj8bxyll5a7ql4y1bkss6gfd8miba4p-astal-battery-0.1.0-dev/share/gir-1.0/AstalBattery-0.1.gir
/nix/store/cvpp0wqy66id5cnyanfps9i73xbn4ihf-astal-0.1.0-dev/share/gir-1.0/Astal-0.1.gir
/nix/store/i7v9wyz5143qkhwk9772ap6g5wybqc6x-astal-auth-0.1.0-dev/share/gir-1.0/AstalAuth-0.1.gir
/nix/store/jh2l0jhdj0j65pz1mc93p6222j57iayv-astal-network-0.1.0-dev/share/gir-1.0/AstalNetwork-0.1.gir
/nix/store/kr2iaxjavqdxiqdy20gywicw2fp1wyg3-astal-bluetooth-0.1.0-dev/share/gir-1.0/AstalBluetooth-0.1.gir
/nix/store/kzkqz7c5yarsf4w3vkpg4kwxrdmmjcb9-astal-mpris-0.1.0-dev/share/gir-1.0/AstalMpris-0.1.gir
/nix/store/n9dmrz55smbs08s0gd9maj144hqfj6j8-astal-river-0.1.0-dev/share/gir-1.0/AstalRiver-0.1.gir
/nix/store/qflrva4jc17viqibnlk8y98ckls6x97i-astal-notifd-0.1.0-dev/share/gir-1.0/AstalNotifd-0.1.gir
/nix/store/s71bnkv12170lxw857amswci2cprb0vx-astal-tray-0.1.0-dev/share/gir-1.0/AstalTray-0.1.gir
/nix/store/wi1sbacbbmxfjzrrpdg0swq2zbi833jp-astal-hyprland-0.1.0-dev/share/gir-1.0/AstalHyprland-0.1.gir
/nix/store/widx0iar251dbarijbrysf1khpni1sg8-astal-power-profiles-0.1.0-dev/share/gir-1.0/AstalPowerProfiles-0.1.gir
/nix/store/z4ikq38121888s9rfmz2zpjca45ykxvw-astal-apps-0.1.0-dev/share/gir-1.0/AstalApps-0.1.gir
```

If you push another change without incrementing the semver, it'l just be multiple versions of each semver with different hashes and no real way to tell which is newer. I might revisit this later, but this doesn't seem reasonably scriptable without tagged versions on nixos unless you don't have astal installed on the machines your building on and garbage collect before every update.

**Comment by Aylur** [comment]
I did not want to tag a release until I'm happy with the state of the project, so lets get back to this later.
In the upcoming weeks I'll shape up the libraries a bit and write up their doc comments after which I plan to tag a release and after that everytime a change happens I'll increase the semver accordingly

**Comment by hyperparabolic** [comment]
Alright, that works. I'll have to give it a try later. Thanks!
