### ISSUE TITLE
Media Player crashes on Gnome Blanker app launch

### ISSUE THREAD

**Issue by danielwerg** [Aylur/astal#170]
**Describe the bug**

[Media Player](https://github.com/Aylur/astal/tree/main/examples/js/media-player) crashes on Gnome Blanker app launch

**To Reproduce**

1. Run [Media Player Example](https://github.com/Aylur/astal/tree/main/examples/js/media-player)
2. Launch [Gnome Blanket](https://apps.gnome.org/Blanket/)
3. See crash

```
(gjs:17130): GLib-CRITICAL **: 16:09:05.260: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed
**
GLib:ERROR:../glib/glib/gvariant-serialiser.c:1554:g_variant_serialised_n_children: code should not be reached
Bail out! GLib:ERROR:../glib/glib/gvariant-serialiser.c:1554:g_variant_serialised_n_children: code should not be reached
error: signal: aborted
```

**Comment by kotontrion** [comment]
Blanket does not follow the mpris spec correctly. I opened an issue about it [here](https://github.com/rafaelmardojai/blanket/issues/367).

**Comment by danielwerg** [comment]
Oh, I see :(

Is there anything that could be done on astal side as workaround?
