### ISSUE TITLE
System Tray Icons getting pixelated for specific apps

### ISSUE THREAD

**Issue by TanR314** [Aylur/astal#174]
SystemTray icon gets pixelated for specific apps like Telegram, Discord

The simple-bar example of astal also has this bug, if you increase the icon size by css
"font-size" property.

**Comment by kotontrion** [comment]
Not sure about telegram, but discord provides its icon only in 24x24 pixels. So when you increase its size above that, it will be upscaled leading to a blurry icon. There is nothing you can do about it.

**Comment by TanR314** [comment]
Okay I also use ignis ( an alternative of ags for python ). Yes discord's icon does get pixelated when using ignis too.
But telegram's icon doesn't get pixelated in ignis. So i guess ags has bug or something about telegram

**Comment by kotontrion** [comment]
could you try with the tray lib from #68 ? this includes various changes and fixes. If this issue persists with that branch, then please reopen this issue.

**Comment by TanR314** [comment]
I didn't understand what tray lib is and how to use it...
