### ISSUE TITLE
How to get player name when `player.busName` is `...playerctld`

### ISSUE THREAD

**Issue by danielwerg** [Aylur/astal#178]
**Have you read through the documentation?**

- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe your question**

How can I get non "prettified" player name when using `...playerctld` for bus name?

Normally I wouldn't need it and just use `identity` but, as show in example below, [lowfi](https://github.com/talwat/lowfi) includes useful information in it's name (current playlist). mpris lib doesn't seem to have a way to get the player name with `playerctld` bus name.

---

`playerctl --list-all`:
```
lowfi.micropop.instance20406
lowfi.lofigirl.instance2726
```

---

`astal-mpris info --player playerctld`

`lowfi.micropop.instance20406`:
```json
[
  {
    "bus_name" : "org.mpris.MediaPlayer2.playerctld",
    "available" : true,
    "identity" : "lowfi",
    "entry" : "dev.talwat.lowfi",
    "supported_uri_schemes" : [
      "https"
    ],
    "loop_status" : "Unsupported",
    "shuffle_status" : "On",
    "rate" : 1.0,
    "volume" : 0.05000000074505806,
    "position" : 2.8086159999999998,
    "cover_art" : null,
    "metadata" : {
      "xesam:title" : "Baby Hotline",
      "mpris:length" : 291000000
    }
  }
]
```

`lowfi.lofigirl.instance2726`:
```json
[
  {
    "bus_name" : "org.mpris.MediaPlayer2.playerctld",
    "available" : true,
    "identity" : "lowfi",
    "entry" : "dev.talwat.lowfi",
    "supported_uri_schemes" : [
      "https"
    ],
    "loop_status" : "Unsupported",
    "shuffle_status" : "On",
    "rate" : 1.0,
    "volume" : 0.050000008195638657,
    "position" : 2.5142850000000001,
    "cover_art" : null,
    "metadata" : {
      "xesam:title" : "Volcano Eye",
      "mpris:length" : 148000000
    }
  }
]
```

Can't identify which player is using lofigirl or micropop playlist. Also for other players I want to add suffix if there more than one present.

Can we have `name` field?

```json5
{
  "bus_name" : "org.mpris.MediaPlayer2.playerctld",
  "available" : true,
  "name": "lowfi.micropop.instance20406",
  "identity" : "lowfi",
  "entry" : "dev.talwat.lowfi",
  // ...
}
```

**Comment by Aylur** [comment]
This name you are referring to is the bus name without the `org.mpris.MediaPlayer2.` prefix. The spec only contains an identity and the desktop entry. It is a limitation of playerctld since it has the busname of `org.mpris.MediaPlayer2.playerctld`. playerctld would have to forward this information in a metadata.

**Comment by Aylur** [comment]
I'm pretty sure that `playerctld` only exists to keep track of the most recent player you have interacted with.
What I would suggest is that you should ignore its bus and just work with the players' interface directly.

**Comment by danielwerg** [comment]
I like to shift players:

https://github.com/user-attachments/assets/2e3aa9f0-a65a-44ff-a34d-d279c711a88a

Either with astal widget or scripts around playerctl and they are both synced.

I wrote function that finds player by matching several keys: identity, entry, title, mpris:length. I guess it will do for now.
