### ISSUE TITLE
How to hide system tray based on apps count

### ISSUE THREAD

**Issue by Nanito111** [Aylur/astal#180]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [ ] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
I'm trying to hide the tray widget when no apps are in the system tray.
I'm using this code that I modified from the repo lua example "simple-bar".
```lua
local function SysTray()
  local tray = Tray.get_default()
  local show_tray = false

  -- this does not print, #tray.items always show 0
  if #tray.items > 0 then
    print("items in tray")
    show_tray = true
  end

  -- this doesn't print anything
  for _, item in ipairs(tray.items) do
    print(item.tooltip_markup)
  end

  return Widget.Box({
    class_name = "Tray",
    visible = show_tray,
    bind(tray, "items"):as(function(items)
      return map(items, function(item)
        if item.icon_theme_path ~= nil then
          App:add_icons(item.icon_theme_path)
        end
        local menu = item:create_menu()

        return Widget.Button({
          tooltip_markup = bind(item, "tooltip_markup"),
          on_destroy = function()
            if menu ~= nil then
              menu:destroy()
            end
          end,
          on_click_release = function(self)
            if menu ~= nil then
              menu:popup_at_widget(self, Gdk.Gravity.SOUTH, Gdk.Gravity.NORTH, nil)
            end
          end,
          Widget.Icon({
            g_icon = bind(item, "gicon"),
          }),
        })
      end)
    end),
  })
end
```

**Describe your question**
Is this a correct behaviour? if this is true, what is the way to do it?

**Comment by kotontrion** [comment]
The items list is initially empty. Items will be added at a later point when apps register their tray icons. Also show_tray never updates.
Therefore you need to bind the visible property as well.

```lua
visible = bind(tray, "items"):as(function(items)
    return #items > 0
end)
```

**Comment by Nanito111** [comment]
thank you for your fast response, I think i need to learn more about binds haha.

I have applied your code and still doesn't hide, maybe this is a bug ¿? I added a print just to check if the function was being executing and still nothing.
```lua
local function SysTray()
  local tray = Tray.get_default()

  return Widget.Box({
    class_name = "Tray",
    visible = bind(tray, "items"):as(function(items)
      print(#items > 0)
      return #items > 0
    end),
    bind(tray, "items"):as(function(items)
      return map(items, function(item)
-- rest of the function --
```
tray with apps (show tray)
![image](https://github.com/user-attachments/assets/6e5cbce6-e320-4fb9-b122-2bc2667d57f5)

tray with no apps (hide tray)
![image](https://github.com/user-attachments/assets/c01076bc-eb8d-487d-8abc-d92631dfe57a)

tray with `visible = false`
![image](https://github.com/user-attachments/assets/fec35504-4cde-4b83-a57d-abe6f3660dcd)

**Comment by tokyob0t** [comment]
Yea, currently using a `binding` with the property `visible` in the constructor doesnt work, you should be able to do it as well using `setup` and `hook`

```lua
local function SysTray()
  local tray = Tray.get_default()

  return Widget.Box({
    class_name = "Tray",
    setup = function(self)
      self:hook(tray, "notify::items", function(_, items)
         self.visible = #items > 0
      end)
    end,
    bind(tray, "items"):as(function(items)
      return map(items, function(item)
-- rest of the function --

```

**Comment by Aylur** [comment]
visible binding fixed in https://github.com/Aylur/astal/commit/a60c44cd0a98b43d03c59107f43910f381644e16
