### ISSUE TITLE
astal.lib.mkLuaPackage is no longer detected by nix

### ISSUE THREAD

**Issue by fitzthomas18** [Aylur/astal#191]
**Describe the bug**
Nix returns `error: attribute 'mkLuaPackage' missing` when trying to build a derivation with astal.lib.mkLuaPackage. I am using the example derivation from the documentation.

**To Reproduce**
Use astal input on or after commit 23083cd 
Try to build a derivation with astal.lib.mkLuaPackage

**Expected behavior**
The derivation builds and outputs a binary to ./result/

**Additional context**
Rolling back to commit 0cf43e5 fixes the issue.

**Comment by Aylur** [comment]
reverted the commit, we will need a bit of nix refactoring anyway where we can redo https://github.com/Aylur/astal/commit/23083cdec69853bc8e480807a5f93b03df340183
