### ISSUE TITLE
refactor nix code

### ISSUE THREAD

**Issue by Aylur** [Aylur/astal#192]
Should've gone with changes from #1 to begin with.

Currently the nix code for docs are a bit of a mess https://github.com/Aylur/astal/pull/166#issuecomment-2526174648
Shared nix code should be in the /nix directory and the derivations from the flake should be moved to each lib's directory in default.nix
aarch64 support is also due #183, but I'm unsure how to handle `lib.mkLuaPackage` #191. Should it stay with `pkgs` being a mandatory argument or should it move to `lib.<arch>.mkLuaPackage`?

**Comment by Aylur** [comment]
@NotAShelf Do you maybe want to have a round two at it?

**Comment by ys5g** [comment]
Sorry if this is annoying, but this means that the idea in [this comment](https://github.com/Aylur/astal/pull/166#issuecomment-2548771530) is out of the question, correct?

**Comment by NotAShelf** [comment]
I currently don't have the time to refactor all Nix code, but I would be happy to review/assist with an incoming PR if there is one.

Note: lib should *not* be versioned (e.g. `lib.<arch>.foo`) - either put those functions in `pkgs`, or pass `system` as an argument to the lib function.
