### ISSUE TITLE
SysTray doesn't work anymore.

### ISSUE THREAD

**Issue by wxqwinner** [Aylur/astal#194]
**Describe the bug**

archlinux after update the libastal-tray-git.
Even if you fix this, it won't work.
https://github.com/Aylur/astal/blob/d7d11b341db85ce9768fa06b6f225d713621ec56/examples/js/simple-bar/widget/Bar.tsx#L23

**To Reproduce**
A description or script to reproduce the behavior:

**Expected behavior**

**Additional context**

**Comment by Aylur** [comment]
https://github.com/Aylur/astal/pull/68
