### ISSUE TITLE
Systray Error

### ISSUE THREAD

**Issue by jlgwch** [Aylur/astal#198]
menubutton cannot be constructed

# error info:
(gjs:23659): Gjs-CRITICAL **: 13:09:33.520: JS ERROR: TypeError: ctors[ctor] is not a constructor
jsx@file:///run/user/1000/ags.js:771:12
SysTray/<.children</<@file:///run/user/1000/ags.js:824:144
SysTray/<.children<@file:///run/user/1000/ags.js:824:111
as/bind2.transformFn@file:///run/user/1000/ags.js:70:34
as/bind2.transformFn@file:///run/user/1000/ags.js:70:40
get@file:///run/user/1000/ags.js:79:21
subscribe/id<@file:///run/user/1000/ags.js:92:23
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

**Comment by Aylur** [comment]
your astal-gjs package is out of date
