### ISSUE TITLE
hpack property of box is missing

### ISSUE THREAD

**Issue by biskyy** [Aylur/astal#200]
**Describe the bug**
in ags v1 you could set the hpack property of a box which would align its children without modifying the box size.

**To Reproduce**
try setting the hpack property of a box. it isn't available
<details>
  <summary>repro code</summary>

```typescript
import { App, Astal, Gtk, Gdk } from "astal/gtk3"
import { bind, Variable } from "astal";

const revealBar = Variable(true)

export default function Bar(gdkmonitor: Gdk.Monitor): JSX.Element {

  return <window
    name="bar"
    gdkmonitor={gdkmonitor}
    layer={Astal.Layer.TOP}
    exclusivity={Astal.Exclusivity.NORMAL}
    anchor={Astal.WindowAnchor.TOP
      | Astal.WindowAnchor.LEFT
      | Astal.WindowAnchor.RIGHT}
    application={App}>
    <eventbox
      onHover={() => revealBar.set(true)}
      onHoverLost={() => revealBar.set(false)}
    >
      <box className="bar" hexpand vexpand>
        <revealer
          transitionType={Gtk.RevealerTransitionType.SLIDE_DOWN}
          transitionDuration={350}
          revealChild={bind(revealBar).as(Boolean)}
        >
          <centerbox hexpand vexpand
            startWidget={<box css="background-color: red;">
              <label label="hi" />
              <label label="hi" />
              <label label="hi" />
            </box>}
            centerWidget={<box css="background-color: black;">
              <label label="hi" />
              <label label="hi" />
              <label label="hi" />
            </box>}
            endWidget={<box css="background-color: blue;" hpack={Gtk.PackType.END}>
              <label label="hi" />
              <label label="hi" />
              <label label="hi" />
            </box>}
        />
        </revealer>
      </box>
    </eventbox>
  </window>
}
```
</details>

**Expected behavior**
hpack property should be available

**Additional context**
1. im not sure whether i submit this issue here or on the ags repo.
2. halign can achieve a similar behavior however it modifies the size of the box and i also cant use hexpand togheter with it.
this is what happens when i use halign
![image](https://github.com/user-attachments/assets/72a1cc8f-94cd-4afd-b3c2-1f5c10dd73c5)

**Comment by Aylur** [comment]
it was an alias for [halign](<https://docs.gtk.org/gtk3/property.Widget.halign.html>), see [example](https://github.com/Aylur/astal/blob/3468763d51d389c67ec7b1a390ffa8a5328bddb6/examples/js/simple-bar/widget/Bar.tsx#L139)

**Comment by biskyy** [comment]
huh.. ok i see👍
