### ISSUE TITLE
[Lua] Tray apps not appearing in SysTray

### ISSUE THREAD

**Issue by Nanito111** [Aylur/astal#202]
**Describe the bug**
Tray apps are not appearing in system tray. When opening a tray app, astal returns error.

**To Reproduce**
1. Start Astal
2. Open tray app (eg.Signal, Slack, Discord, etc)

**Expected behavior**
To not show app, and return this error.
```
(lua:12177): Lgi-WARNING **: 10:05:05.700: Error raised while calling 'lgi.cbk (function: 0x5e10fda59a00): GObject': ./widget/Bar.lua:22: attempt to call a nil value (field 'MenuButton')

(lua:12177): Lgi-WARNING **: 10:05:05.701: Error raised while calling 'lgi.cbk (function: 0x5e10fdbf6650): GObject': ./widget/Bar.lua:22: attempt to call a nil value (field 'MenuButton')
```

**Additional context**
SysTray code (same code from examples/)
```lua
local function SysTray()
  local tray = Tray.get_default()

  return Widget.Box({
    class_name = "SysTray",
    bind(tray, "items"):as(function(items)
      return map(items, function(item)
        return Widget.MenuButton({
          tooltip_markup = bind(item, "tooltip_markup"),
          use_popover = false,
          menu_model = bind(item, "menu-model"),
          action_group = bind(item, "action-group"):as(function(ag)
            return { "dbusmenu", ag }
          end),
          Widget.Icon({
            gicon = bind(item, "gicon"),
          }),
        })
      end)
    end),
  })
end
```
**Versions**
- Astal 0.1.0
  - libastal-git r624.6fbeb92-1
  - libastal-lua-git r624.6fbeb92-1

**Comment by kotontrion** [comment]
Update.
The tray had a breaking change recently.
You are trying to do it the new way, but use a commit from before the breaking change.

**Comment by Nanito111** [comment]
Thank you and sorry, I thought that I had astal up to date 🤦🏻‍♂️, I update astal and it worked.

I'll close the issue.
