### ISSUE TITLE
How to reload astal widgets on the fly

### ISSUE THREAD

**Issue by mylinuxforwork** [Aylur/astal#203]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)
Yes

**Describe what have you tried so far**
I want to reload the astal configuration mainly the style.css on the fly WITHOUT using

```
ags quit &
sleep 0.2
ags run &
```

**Describe your question**
Is there a way to reload the stylesheet of my widgets without killing and running astal again?

**Comment by kotontrion** [comment]
https://aylur.github.io/astal/guide/typescript/theming#apply-stylesheets-at-runtime

**Comment by mylinuxforwork** [comment]
@kotontrion Thanks. But can this be done from a bash script outside of the widget implementation?

**Comment by kotontrion** [comment]
You can implement a request handler, so you can use the cli tool to invoke it.
https://aylur.github.io/astal/guide/typescript/cli-app#messaging-from-cli

Another approach would be to monitor the css files for changes and reapply them automatically on change
https://aylur.github.io/astal/guide/typescript/utilities#monitoring-files

**Comment by danielwerg** [comment]
https://github.com/Aylur/astal/pull/91
