### ISSUE TITLE
how to draw in <drawingarea /> ??

### ISSUE THREAD

**Issue by Sk7Str1p3** [Aylur/astal#206]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
None, i could not find any useful info in references

**Describe your question**
My goal is Cava widget on bar, as i understood only drawingarea can be used for best effect, but i have no idea and info how do i use it.

**Comment by kotontrion** [comment]
https://github.com/Aylur/astal/issues/140#issuecomment-2505567297
