### ISSUE TITLE
Unable to Create Context Menu (Using GTK 3)

### ISSUE THREAD

**Issue by CodeBulletin** [Aylur/astal#210]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
I have tried doing this 
export const Menu = astalify(Gtk.Menu)
export const MenuItem = astalify(Gtk.MenuItem)

And Got The Following Error
Gtk-WARNING **: 08:54:23.882: Attempting to add a widget with type Astal_Gtk_Menu to a container of type Window, but the widget is already inside a container of type GtkWindow, please remove the widget from its existing container first.

**Describe your question**
I was trying to create a right click context menu. I don't know how to do that. I cant find it in docs

**Comment by Aylur** [comment]
Menu is a toplevel window itself, you cannot add it to a window
https://docs.gtk.org/gtk3/class.Menu.html
