### ISSUE TITLE
Problem Initiating With GTK4

### ISSUE THREAD

**Issue by ShadowS0ng** [Aylur/astal#211]
**Have you read through the documentation?**
- [ x ] [Astal docs](https://aylur.github.io/astal/)
- [ x ] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [ x ] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
I tried using `GTK4Layershell.init_for_window()` without success

**Describe your question**
How can i initiate a project with gtk4? I change the `tsconfig` and import modules from GTK4 but the problem is when i try to run the app i get error `can not set monitor on window: layer shell not supported
tip: running from an xwayland terminal can cause this, for example VsCode` 
I have gtk4-layer-shell installed and i suppose i have to initiate it somehow?? or is there another way? how should i use gtk4.
I'm using TS for writing widgets.

**Comment by kotontrion** [comment]
you have to use the `--gtk4` flag for `ags run`
Also while all widgets are visible default, that is not true for windows, so either call show on it after creation, or set the visible property to true on construction.
