### ISSUE TITLE
add a exit signal to AstalIO.Process

### ISSUE THREAD

**Issue by kotontrion** [Aylur/astal#214]
When a AstalIO.Process is started there is no way to know when it exits. There are signals for stdout and stderr, but you can't use those to indicate if the process did exit.

**Comment by Aylur** [comment]
The intended usage is that `subprocess` runs indefinitely or until explicitly killed, so only the `stderr` and `stdout` signals are needed, while `exec_async` is expected to quit after which you only need the full output and so `stdout` means it quit successfully and `stderr` means there was an error. `exec` is similar to `exec_async` but with immediate return values and errors.

We can technically add an `exit` signal, but it would only make sense for `subprocess` and only in the case when you expect it to fail at some point which should not happen in a real situation.

**Comment by kotontrion** [comment]
I need to write to the processes stdin, so `exec_async` is not an option. But providing a way to write to stdin of a process created by `exec_async` would work for me as well.

**Comment by Aylur** [comment]
Is there an issue with [write_async](https://aylur.github.io/libastal/io/method.Process.write_async.html)?
Edit: oh, it only works with `subprocess`

**Comment by kotontrion** [comment]
To use that i need to use AstalIO.Process, but then i don't know when the process finishes. If i use `exec_async` i know when the process finishes, but then i cant't write to stdin.
