### ISSUE TITLE
(Clarify) Installing on NixOS

### ISSUE THREAD

**Issue by HiImJulien** [Aylur/astal#30]
Hey there!

First of all, thank you very much for your efforts! I love your project.

Now on to the issue. I am stuck at properly setting up Astal / Ags v2 on my NixOS machine.
My flake currently looks like this:

```nix
# FILE: flake.nix

inputs = {
  ags.url = "github:aylur/ags/v2";
}

# ---------

# FILE: home/ags.nix (imported by home manager)

{ inputs, pkgs, config, ...}:

{
  imports = [
    inputs.ags.homeManagerModules.default
  ];

  programs.ags = {
    enable = true;
    extraPackages = with pkgs; [
      inputs.ags.packages
      accountsservice
    ];
  };
}
```

Running any ags related command exits with the following error:

> error: executable "astal" not found in $PATH

Do I need to install astal separately as described in the Wiki?
If so, which Language should I choose, when I want to create my config using GJS/JSX?

**Comment by adminy** [comment]
try this:
```bash
mv $HOME/.config/ags $HOME/.config/ags_old
ags --init
ags
```

also in your flake.nix to stay more up to date add the following inputs:
```nix
inputs = {
    ...;
    astal = { url = "github:Aylur/astal"; inputs.nixpkgs.follows = "nixpkgs"; }; # ags backend
    ags = { url = "github:Aylur/ags/v2"; inputs.astal.follows = "astal"; inputs.nixpkgs.follows = "nixpkgs"; }; # task bar
};

...

  imports = [ inputs.ags.homeManagerModules.default ];
  programs.ags = {
    enable = true;
     extraPackages = with inputs.ags.packages.${pkgs.system}; [
      apps auth bluetooth hyprland mpris network notifd powerprofiles river tray wireplumber battery pkgs.fzf
      inputs.astal.packages.${pkgs.system}.default
    ];
  };
```

but I think your config should work just fine, its the way the ags project is set up in $HOME/.config/ags, you are missing some tsconfig.json configuration.
