### ISSUE TITLE
[Notifd] Notification expired behavior

### ISSUE THREAD

**Issue by PoSayDone** [Aylur/astal#32]
After the notification display time expires, the notification disappears completely from the notification list. 
Is this the correct behavior? 
If so, how should notifications be saved if they have not been manually closed by the user?

**Comment by Aylur** [comment]
Yes this is to be expected. The spec says that notifications can specify an expire time, which after they should be removed regardless of user input.
You can set the daemon to ignore expiration by setting `ignore-timeout`:
```js
const notifd = Notifd.get_default()
notifd.ignoreTimeout = true
```

**Comment by PoSayDone** [comment]
Thank you!
