### ISSUE TITLE
`battery-icon-name` messed up at 95-99% when charging

### ISSUE THREAD

**Issue by brainlessbitch** [Aylur/astal#36]
**Describe the bug**
Title basically says it all, at 95 to 99 percent the icon is `battery-level-100-chargning-symbolic` which isn't a valid icon, this seems to be an issue with how vala does rounding

**To Reproduce**
Wait for your battery to get to 95 to 99 percent while charging

**Expected behavior**
I guess for the battery icon to go to `battery-level-100-charged-symblic`, or for it to stay at `battery-level-90-charging-symblic`

**Comment by tokyob0t** [comment]
thats when you use `battery-icon-name`, isn't it? if you use `icon-name` it should work better

**Comment by brainlessbitch** [comment]
but i’m not using `icon-name` cause it doesn’t accurately show the battery percent, so i use `battery-icon-name`
