### ISSUE TITLE
Gtk.EventBox doesnt receive "drop" events

### ISSUE THREAD

**Issue by tokyob0t** [Aylur/astal#37]
**Describe the bug**
Gtk.EventBox doesnt receive "drop" events if its in a Layer Shell

**To Reproduce**
```lua
Widget.Window({
	Widget.EventBox({
		css = "background: red;",
		width_request = 150,
		height_request = 150,
		setup = function(self)
			self:drag_dest_set(Gtk.DestDefaults.ALL, {}, Gdk.DragAction.COPY)
			self:drag_dest_add_text_targets()
		end,
		on_drag_data_received = function(_, _, _, _, data)
			print(data:get_text())
		end,
	}),
})
```
And from a file explorer drop an image

**Expected behavior**
If I drop an image or any file from a file explorer, the path should be printed

**Additional context**
Works if its in a normal Gtk.Window

**Comment by Aylur** [comment]
I also experienced this issue some time ago, I think this is a gtk-layer-shell bug

Does it work if you do a drop from the same window?

**Comment by kotontrion** [comment]
In my AGS v1  config I have a working drop target. So it is definitely not a gtk-layer-shell bug. 
Differences which come to mind is that my drop target is a TextView not an eventbox and my window has keymode exclusive set.

**Comment by tokyob0t** [comment]
Works after i use `keymode = "EXCLUSIVE"` :P
