### ISSUE TITLE
Just how exactly does one start Astal through AGS?

### ISSUE THREAD

**Issue by Eleshz** [Aylur/astal#45]
**Have you read through the documentation?**
- [ ] [Astal docs](https://aylur.github.io/astal/)
- [ ] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [ ] [FAQ](https://aylur.github.io/astal/guide/ags/faq)
- [X] Yes I have, for over an hour now

**Describe what have you tried so far**

Unlike AGS, Astal is obviously a bit more complicated in its early state. I thought that like AGS, I could simply use a ‘config.js’ *esk* file to get going. For the life of me I can’t even get the .js example up and running, I just cannot figure it how to start it. I’m aware this is a major skill issue, and it’s probably just a simple fix, but I’m still heavily struggling. 

**Describe your question**

Simply this, how does one move from the installation (that I’ve completed), to running the example .js bar?

**Comment by ghost** [comment]
EDIT: after #46 I'm not sure this works anymore
~~If you mean the example in this repo, you just need to~~

~~1. Install all the libraries required(audio, battery, Hyprland, mpris, network, tray, and WirePlumber)
2. Add a tsconfig.json file to the directory of that example~~
<details>
<summary>Example tscfg</summary>

```json
{
    "$schema": "https://json.schemastore.org/tsconfig",
    "compilerOptions": {
        "experimentalDecorators": true,
        "strict": true,
        "target": "ES2023",
        "moduleResolution": "Bundler",
        "jsx": "react-jsx",
        "jsxImportSource": "<where astal is installed>/src/jsx",
        "paths": {
            "astal": ["<where astal is installed>"],
            "astal/*": ["<where astal is installed>/src/*"]
        }
    }
}
```
</details>

**Comment by Aylur** [comment]
It is still as simple as a single file to get started e.g `app.js` or `app.ts`, only difference is that a tsconfig.json file is also needed, but ags will generate one for you.

<https://aylur.github.io/astal/guide/ags/first-widgets#getting-started>

![image](https://github.com/user-attachments/assets/b613b55e-7b10-408e-964c-503eca0cabb6)

There are multiple ways to start writing code with or without AGS, as Astal consists of multiple separate packages.

After https://github.com/Aylur/astal/pull/46 I'll document more thoroughly how you can setup an environment without ags too

**Comment by Eleshz** [comment]
Thank you, I’ll see what I can figure out
