### ISSUE TITLE
Album cover with Mpris: Failed to cache cover art with url

### ISSUE THREAD

**Issue by Lap1n** [Aylur/astal#52]
**Describe the bug**
When using the Mpris library (provided [sample bar](https://github.com/Aylur/astal/tree/main/examples/js/simple-bar)), I get the following error with the spotify client:
`player.vala:304: Failed to cache cover art with url "https://i.scdn.co/image/<THE_ALBUM_COVER_ID>": Operation not supported`
The song title does show correctly and the url does resolve to a valid image (with wget).

**To Reproduce**
- Use config from [here](https://github.com/Aylur/astal/tree/main/examples/js/simple-bar).
- Spotify is running
- Start ags

**Expected behavior**
Album cover art showing in the bar

**Additional context**
- I am using NixOS, one hypothesis could be that there is some permission issues related to the album cache?
- I followed those steps to install [Ags v2](https://aylur.github.io/astal/guide/getting-started/nix#ags).

**Comment by rubiin** [comment]
try to install gvfs. I had similar log
