### ISSUE TITLE
Window names not applied to layer-shell namespace

### ISSUE THREAD

**Issue by KZDKM** [Aylur/astal#55]
**Describe the bug**

In ags v1, the layer-shell would be named after their window names. Astal defaults every layer to gtk-layer-shell:

```
$ hyprctl layers                                                                                                                    ~
Monitor DP-1:
	Layer level 0 (background):
		Layer 5946a38b17c0: xywh: 1000 162 2560 1440, namespace: gtk-layer-shell
	Layer level 1 (bottom):
	Layer level 2 (top):
		Layer 5946a38b1b50: xywh: 1000 162 2560 28, namespace: gtk-layer-shell
	Layer level 3 (overlay):


Monitor HDMI-A-1:
	Layer level 0 (background):
		Layer 5946a386c8b0: xywh: 0 0 1000 1600, namespace: gtk-layer-shell
	Layer level 1 (bottom):
	Layer level 2 (top):
	Layer level 3 (overlay):

```

**To Reproduce**
A description or script to reproduce the behavior:
Initialize a window (layer) with custom name

**Expected behavior**
layer-shell to be set according to their name and not `gtk-layer-shell`

**Comment by Aylur** [comment]
its a separate prop in Astal https://aylur.github.io/libastal/astal3/property.Window.namespace.html

**Comment by KZDKM** [comment]
My bad, should've rtfm. Looking forward to ags v2 release!
