### ISSUE TITLE
Lua package won't run on Nix Flake

### ISSUE THREAD

**Issue by Daru-san** [Aylur/astal#59]
**Describe the bug**

I have been trying to get astal running with lua on nix using a flake, [here](https://github.com/Daru-san/snow-shell/blob/main/flake.nix). 
It cannot seem to run though, giving this error:
```
/nix/store/s8pjlv398af53048bfcla13cpaxwfaxg-lua-5.2.4/bin/lua: ...g19zz63sr8ryp-lua-5.2.4-env/share/lua/5.2/widget/Bar.lua:1: module 'astal' not found:
```

**To Reproduce**

1. Package astal lua in a flake.
2. Nix build (Succeeds)
3. Run `./result/bin/astal-lua` 

**Expected behavior**

Bar should launch successfully.

**Comment by Aylur** [comment]
https://github.com/Aylur/astal/commit/4a5308c82e0134f87b7e1ccc56e4fa2778b69fdd
