### ISSUE TITLE
Network.get_default() case segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wuliuqii** [Aylur/astal#6]
1. installed ags based on https://aylur.github.io/astal/getting-started/nix#astal
2. add `const network = Network.get_default()` to app.js
3. exec `ags`
```shell
~/.config/ags via  v20.17.0 
› ags
error: signal: segmentation fault (core dumped)
```

But when I remove step 2, it works fine.

![image](https://github.com/user-attachments/assets/a950f17c-c2d3-4190-a4ea-a50f039cf071)

**Comment by wuliuqii** [comment]
I looked at the [source code](https://github.com/Aylur/astal/blob/e9f9de6ba557de6a553f03de813af0fdbdbec047/lib/network/network.vala#L64) and found that `valid.get(0)` may be out of bounds when valid is empty.

I don't know the vala language, but I wrote a demo to test it out：
```vala
class Demo.HelloWorld : GLib.Object {
    public static int main(string[] args) {
        GenericArray<string> array = new GenericArray<string> ();
        print("%s\n", array.get(0));
        return 0;
    }
}
```
And compiling it does cause an out-of-bounds error:
```shell
› valac hello.vala
› ./hello
fish: Job 1, './hello' terminated by signal SIGSEGV (Address boundary error)
```

After I modified get_device and it works fine
```vala
    private NM.Device get_device(NM.DeviceType t) {
        var all = client.get_devices();

        foreach (var device in all) {
            if (device.device_type == t && device.active_connection != null)
                return device;
        }

        return all.get(0);
    }
```
![image](https://github.com/user-attachments/assets/4724f6fe-fcc7-49f7-8b97-12bba1d0c0e2)

**Comment by navidmafi** [comment]
I still get segfaults when switching networks just by doing `const {wifi, wired} = AstalNetwork.get_default();`

example:
```tsx
import AstalNetwork from "gi://AstalNetwork?version=0.1";

export default function () {
    const {wifi, wired} = AstalNetwork.get_default();

    return null
}
```

version: master build (ags+gnim+astal libs)

I have a 110MB coredump which I'm willing to send in private.

Can we re-open this?
