### ISSUE TITLE
gir bindings for WindowAnchor are incorrect

### ISSUE THREAD

**Issue by onlycs** [Aylur/astal#67]
using astal_window_set_anchor, and adding values from Anchor (0 = None, 1 = Top, 2 = Right, 4 = Bottom, and 8 = Left), is incorrect.
after thorough testing, I have found that the correct values are 0 = None, 1 = [seemingly unused, probably center], 2 = Top, 4 = Right, 8 = Bottom, 16 = Left.

passing in these values (and the sums of these values) into astal_window_set_anchor gives the correct values.

I am referencing lines 21-27 from `/usr/share/gir-1.0/Astal-3.0.gir` on arch linux.

**Comment by Aylur** [comment]
|identifier|value|
|-|-|
|ASTAL_WINDOW_ANCHOR_NONE|1|
|ASTAL_WINDOW_ANCHOR_TOP|2|
|ASTAL_WINDOW_ANCHOR_RIGHT|4|
|ASTAL_WINDOW_ANCHOR_LEFT|8|
|ASTAL_WINDOW_ANCHOR_BOTTOM|16|

you should not have to care about their actual values, just use the enum

```js
const { TOP, LEFT, RIGHT } = Astal.WindowAnchor
window.set_anchor(TOP | LEFT | RIGHT)
```

**Comment by onlycs** [comment]
When `gir` generates rust bindings, it generates the values described in the `Astal-3.0.gir` file, which are wrong. Using those values do not work as expected.

**Comment by Aylur** [comment]
the table I commented are their values from the gir file which are correct

**Comment by onlycs** [comment]
I had an old update, lol. Was running r538, updated to r554 and works fine
