### ISSUE TITLE
Building on Gentoo fails.

### ISSUE THREAD

**Issue by ghost** [Aylur/astal#72]
**Describe the bug**
Building on Gentoo fails with the error `FileNotFoundError: [Errno 2] No such file or directory: 'valadoc'` even though valadoc is installed.

**To Reproduce**
- Try compiling with valadoc installed via portage.

**Expected behavior**
The build to succeed.

**Additional context**
This is caused by [lib/gir.py](https://github.com/Aylur/astal/blob/2a9bb96f056f25c95b330984cfe7ac484db6c9c6/lib/gir.py), [lib/astal/io/gir.py](https://github.com/Aylur/astal/blob/2a9bb96f056f25c95b330984cfe7ac484db6c9c6/lib/astal/io/gir.py), and [lib/astal/gtk4/gir.py](https://github.com/Aylur/astal/blob/2a9bb96f056f25c95b330984cfe7ac484db6c9c6/lib/astal/gtk4/gir.py) running the `valadoc` command, but on Gentoo valadoc is installed as `valadoc-${version}`.

**Comment by ghost** [comment]
This can be resolved using a [patch](https://wiki.gentoo.org/wiki//etc/portage/patches), though similar issues may appear with other package managers.

**Comment by srdusr** [comment]
On Gentoo the vala binaries seem to be named with their version numbers, ie:

```bash
$ ls /usr/bin/vala<use_completion_binding>
```

Produces:

 -- file --
valac-0.56*                valadoc-0.56*                   vala-gen-introspect-0.56*


Solution:
To make these binaries accessible using the generic names (e.g., valac, valadoc), you can create symbolic links.

```bash
$ sudo ln -s /usr/bin/valac-<your-version> /usr/bin/valac
$ sudo ln -s /usr/bin/valadoc-<your-version> /usr/bin/valadoc
$ sudo ln -s /usr/bin/vala-gen-introspect-<your-version> /usr/bin/vala-gen-introspect
```
