### ISSUE TITLE
Vala example wont compile,saying astal-tray not in Vala directories or GObject gir dirs

### ISSUE THREAD

**Issue by sheikh1233** [Aylur/astal#86]
**Describe the bug**

After following the installation instructions for all the libraries in astal, trying to compile the vala example bar leads to the error in the title.

**To Reproduce**
A description or script to reproduce the behavior:

Compile the vala example with the meson commands used to install the astal libraries

**Expected behavior**

An executable to be created of the bar

**Additional context**

on Gentoo Linux, compiled libraries from source

**Comment by kotontrion** [comment]
fixed in https://github.com/Aylur/astal/commit/984d9e95ad6796f0028722aba82be0a17a334164

**Comment by sheikh1233** [comment]
ty
