### ISSUE TITLE
Different licenses in files

### ISSUE THREAD

**Issue by ratson** [Aylur/astal#89]
LGPL-2.1: https://github.com/Aylur/astal/blob/main/docs/default.nix#L33
GPL-3: https://github.com/Aylur/astal/blob/main/lang/lua/astal-dev-1.rockspec#L11
GPL: https://github.com/Aylur/astal/blob/main/lang/gjs/package.json#L7

Is that intentional?

**Comment by Aylur** [comment]
oh, thanks for catching it
it was initially gpl3, but after a short time into development we swapped to lgpl-2.1 and I forgot about the lua and js package
