### ISSUE TITLE
How to implement a calendar widget?

### ISSUE THREAD

**Issue by mylinuxforwork** [Aylur/astal#93]
**Have you read through the documentation?**
- [ y] [Astal docs](https://aylur.github.io/astal/)
- [y ] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [y ] [FAQ](https://aylur.github.io/astal/guide/ags/faq)

**Describe what have you tried so far**
I am using ags in my configuration and v1 included the possibility to add a calendar widget.

**Describe your question**
Is there a way with astral to generate a similar calendar widget? Couldn’t find it in the shipped widget list.

**Comment by PoSayDone** [comment]
Works for me
```js
import { GObject } from "astal";
import { astalify, ConstructProps, Gtk } from "astal/gtk3";

class Calendar extends astalify(Gtk.Calendar) {
	static {
		GObject.registerClass(this);
	}

	constructor(
		props: ConstructProps<Gtk.Calendar, Gtk.Calendar.ConstructorProps>,
	) {
		super(props as any);
	}
}

export default () => {
	return (
		<box className={"calendar"}>
			{new Calendar({ hexpand: true, vexpand: true })}
		</box>
	);
};
```

**Comment by mylinuxforwork** [comment]
@PoSayDone Great. Thank you. Will try later.

**Comment by Aylur** [comment]
https://aylur.github.io/ags/guide/migrate.html#widgets
https://docs.gtk.org/gtk3/class.Calendar.html
