### ISSUE TITLE
Detect mouse scroll direction on button

### ISSUE THREAD

**Issue by danielwerg** [Aylur/astal#94]
**Have you read through the documentation?**

- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/ags/faq)

**Describe what have you tried so far**

```tsx
<button
  cursor='pointer'
  onScroll={(_, event) => print(event.direction)}
>
  <label label='scroll me' />
</button>
```

**Describe your question**

Trying to implement wireplumber volume change on mouse scroll up/down, same way I have it setup in waybar:

https://github.com/user-attachments/assets/c1a5f327-886d-4363-8059-f2050c31a505

I'm always getting `4`, no matter what direction I scroll. Looking at [GTK docs on this](https://docs.gtk.org/gdk3/enum.ScrollDirection.html) `4` = `GDK_SCROLL_SMOOTH`

Do I need to fake scrolling area somehow in order for this to work or is there a nicer way to do this?

**Comment by Aylur** [comment]
I don't remember what `direction` is for exactly, but you can use `delta_y` and `delta_x` to determine direction

**Comment by danielwerg** [comment]
I think I tested `delta_x` twice instead of testing `delta_y`, thanks ;D

```tsx
onScroll={(_, event) => print(event.delta_y > 0 ? 'down' : 'up')}
```

**Comment by kulothunganug** [comment]
```jsx
function BN() {
    const brightness = Brightness.get_default();

    return <image
        iconName="display-brightness-symbolic"
        tooltipText={bind(brightness, "screen").as((v) => Math.round(v * 100).toString())}
        onScroll={(_, event) => {
            print(event)
        }}
    />
}
```

For me the event is a number type and it is always 0 no matter what direction i scroll

ags version 2.3.0
installed using aur `aylurs-gtk-shell` package
