### ISSUE TITLE
Hyprland: How to get workspaces per monitor when using `split-monitor-workspaces`?

### ISSUE THREAD

**Issue by iCultureBud** [Aylur/astal#97]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/ags/faq)

**Describe what have you tried so far**
I'm trying to configure my own bar/panel for with AGS on Hyprland. I set up the workspaces with a `Hyprland` object from `gi://AstalHyprland` and already read through the source code.

**Describe your question**
I really don't know if it is a question or a request. I want to only show those workspaces from Hyprland of the current monitor, because I am using the `split-monitor-workspaces` plugin.

**Comment by kotontrion** [comment]
the `workspaces` property includes all workspaces. You have to filter this list using the workspaces monitor property:

```js
<box>
{bind(hyprland, "workspaces")
    .as(wss => wss.filter(ws => /*check monitor using ws.get_monitor()*/ ))
    .as(ws => ws.map(WorkspaceWidget))}
</box>
```

**Comment by iCultureBud** [comment]
Thank you. That's what I already had, but didn't know how to get the current monitor in a widget. I found your [comment](https://github.com/Aylur/ags/issues/363#issuecomment-2140092162) in `ags` and with this funtion it work's perfect :)

So thank you twice :D

**Comment by uwidev** [comment]
Something I noticed when inspecting a the top-level window object for a widget is that has a "monitor" property. Could we somehow reference this property during creation and use it to determine if a workspace is in a this window's monitor property?

I'm not familiar with js, so I'm not too sure if this is possible.

**Comment by kotontrion** [comment]
The monitor property of the window refers to the index of the monitor in the monitors array, and therefore is not  compatible with hyprlands monitor id. It is the same initially, but breaks down as soon as monitors are connect/disconnected.
