### ISSUE TITLE
Windows not visible after a monitor power cycle

### ISSUE THREAD

**Issue by noib3** [Aylur/astal#99]
**Describe the bug**

Astal windows disapper after a monitor is turned off.

**To Reproduce**

I'm using a single external monitor. I'm not sure if it can be reproduced on a laptop by closing and opening the lid.

- WM: Hyprland v0.44.1
- Astal config: the default one after executing `ags init` ([link](https://github.com/noib3/dotfiles/tree/19bc54bc66279502445d296a80d0e1809b077d92/modules/home/astal) to mine)
- `ags bundle`
- run the executable
- turn the monitor off
- turn the monitor on
- 💥 the executable continues running, but the bar has disappeared

**Expected behavior**

The bar is still visible after the monitor is turned back on.

**Comment by kotontrion** [comment]
When you power off your monitor it will be disconnected. Windows bound to a specific monitor will get destroyed when that monitor gets disconnected. Not destroying that window would violate the layer shell protocol and is done automatically by the gtk-layer-shell library.

You need to connect to the monitor added and removed events to recreate the windows:

```js
        //create windows for already connected monitors
        App.get_monitors().map(Bar)
        //create windows for newly connected monitors
        App.connect("monitor_added", (_, mon) => Bar(mon))
       //remove windows for removed monitors
        App.connect("monitor_removed", (_, mon) => {
            App.get_windows().forEach(w => {
                if(w.gdkmonitor == mon) App.remove_window(w)
            })
        })

```

**Comment by Aylur** [comment]
https://aylur.github.io/astal/guide/typescript/faq#auto-create-window-for-each-monitor

**Comment by sadorowo** [comment]
> When you power off your monitor it will be disconnected. Windows bound to a specific monitor will get destroyed when that monitor gets disconnected. Not destroying that window would violate the layer shell protocol and is done automatically by the gtk-layer-shell library.
> 
> You need to connect to the monitor added and removed events to recreate the windows:
> 
>         //create windows for already connected monitors
>         App.get_monitors().map(Bar)
>         //create windows for newly connected monitors
>         App.connect("monitor_added", (_, mon) => Bar(mon))
>        //remove windows for removed monitors
>         App.connect("monitor_removed", (_, mon) => {
>             App.get_windows().forEach(w => {
>                 if(w.gdkmonitor == mon) App.remove_window(w)
>             })
>         })

hello, sorry for commenting in a closed issue, but I don't know how to do it properly. AGS reports that either monitor-added/monitor_added isn't a valid AstalJS signal. Are there any changes in GTK4 related to this (I know that this example is based on GTK3)? Thanks

```
(gjs:180200): Gjs-CRITICAL **: 20:37:24.861: JS ERROR: Error: No signal 'monitor_added' on object 'AstalJS'
main@file:///run/user/1000/ags.js:1045:19
mkApp/start/<@file:///run/user/1000/ags.js:642:15
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
```
